engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
    checks:
      Similar code:
        enabled: false
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      no-multiple-empty-lines:
        enabled: false
exclude_paths:
- "templates/"
ratings:
   paths:
   - "server/**/*"
   - "server/*"